// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";

export interface IPhotoFields {
  /** photo */
  photo: Asset;

  /** Size */
  size: "L" | "S";
}

export interface IPhoto extends Entry<IPhotoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "photo";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISessionFields {
  /** Nome */
  name?: string | undefined;

  /** Descrição */
  description?: string | undefined;

  /** slug */
  slug?: string | undefined;

  /** medias */
  medias: (IPhoto | IVideo)[];
}

/** Por exemplo BOOK I, BOOK II, etc */

export interface ISession extends Entry<ISessionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "session";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISettingsFields {
  /** Intro URL */
  introUrl?: string | undefined;
}

/** Aqui vão as informações que aparecem quando alguem compartilha nas redes sociais */

export interface ISettings extends Entry<ISettingsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "settings";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IVideoFields {
  /** vimeo_url */
  vimeoUrl?: string | undefined;
}

export interface IVideo extends Entry<IVideoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "video";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "photo" | "session" | "settings" | "video";

export type IEntry = IPhoto | ISession | ISettings | IVideo;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
