// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IProjectFields {
  /** Title */
  title: string;

  /** Short Description */
  shortDescription?: Document | undefined;

  /** video url */
  videoUrl?: string | undefined;

  /** Home Image */
  homeImage: Asset;

  /** header image */
  headerImage?: Asset | undefined;

  /** Body */
  body?: Document | undefined;

  /** Home Layout */
  homeLayout?: "two columns" | "full width" | "with mask" | undefined;
}

export interface IProject extends Entry<IProjectFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "project";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "project";

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
